import type { LegalSection } from "@/components/legal/LegalDocument";

export const PRIVACY_INTRO = [
  "BadePay (“BadePay”, “we”, “us”, or “our”) is committed to protecting the privacy and security of your personal information. This Privacy Policy explains how we collect, use, disclose, store, and protect your information when you access or use the BadePay mobile application, website, payment services, and related products and services (collectively, the “Services”).",
  "By accessing or using BadePay, you acknowledge that you have read and understood this Privacy Policy.",
];

export const PRIVACY_SECTIONS: LegalSection[] = [
  {
    id: "who-we-are",
    title: "1. Who We Are",
    blocks: [
      { p: "BadePay is a digital payment platform that enables users and merchants to make and receive payments through supported payment channels, including QR-based payments and other services that may be introduced from time to time." },
    ],
  },
  {
    id: "information-we-collect",
    title: "2. Information We Collect",
    blocks: [
      { p: "Depending on how you use BadePay, we may collect the following categories of information." },
      { h: "2.1 Personal Information" },
      { p: "We may collect information such as:" },
      { list: ["Full name", "Date of birth", "Gender, where required", "Phone number", "Email address", "Residential or business address", "Username and account information", "Profile information", "Contact preferences"] },
      { h: "2.2 Account and Authentication Information" },
      { p: "When you create or access a BadePay account, we may collect:" },
      { list: ["Login credentials", "PIN or authentication information", "One-time passwords (OTP)", "Authentication tokens", "Security questions or other verification information"] },
      { p: "BadePay does not intentionally store your complete payment card PIN or other sensitive authentication credentials in plain text." },
      { h: "2.3 Identity and KYC Information" },
      { p: "Where required by applicable laws, regulations, payment partners, financial institutions, or our compliance obligations, we may collect and verify information such as:" },
      { list: [
        "Government-issued identification",
        "National Identification Number (NIN), where legally permitted and required",
        "Bank Verification Number (BVN), where legally permitted and required",
        "Passport or other identification documents",
        "Facial or biometric information where legally required and appropriately processed",
        "Proof of address",
        "Business registration information",
        "Tax or business identification information",
        "Information required for Know Your Customer (KYC), Anti-Money Laundering (AML), and fraud-prevention checks",
      ] },
      { p: "We will only request information that is reasonably necessary for the relevant purpose." },
      { h: "2.4 Transaction Information" },
      { p: "When you make or receive a payment through BadePay, we may collect information relating to the transaction, including:" },
      { list: ["Transaction amount", "Date and time of transaction", "Transaction reference", "Sender and recipient information", "Merchant information", "Payment method", "Transaction status", "QR code information", "Refund and reversal information", "Payment history"] },
      { h: "2.5 Financial and Payment Information" },
      { p: "Depending on the payment services you use, we may process information relating to:" },
      { list: ["Bank accounts", "Payment cards", "Payment instruments", "Financial institutions", "Payment provider information", "Account identifiers and related payment details"] },
      { p: "Where payment processing is performed by a third-party payment processor or financial institution, that provider may process payment information in accordance with its own privacy policy and applicable regulatory requirements." },
      { h: "2.6 Device and Technical Information" },
      { p: "When you use BadePay, we may automatically collect technical information such as:" },
      { list: ["Device type", "Device model", "Operating system", "Browser type", "IP address", "Mobile network information", "Unique device identifiers", "App version", "Language and regional settings", "Date and time of access", "Crash reports", "Log information", "Security and fraud-detection information"] },
      { h: "2.7 Location Information" },
      { p: "Where necessary and where permitted by law, BadePay may collect approximate or precise location information." },
      { p: "Location information may be used for purposes such as:" },
      { list: ["Fraud prevention", "Security monitoring", "Providing location-related services", "Identifying nearby merchants", "Improving the Services"] },
      { p: "You may be able to control location permissions through your device settings." },
      { h: "2.8 Communications" },
      { p: "If you contact us or communicate with our support team, we may collect:" },
      { list: ["Emails", "Chat messages", "Support requests", "Call records where legally permitted", "Feedback", "Complaints", "Other communications you send to us"] },
    ],
  },
  {
    id: "how-we-collect",
    title: "3. How We Collect Information",
    blocks: [
      { p: "We may collect information:" },
      { list: [
        "Directly from you when you register or use BadePay",
        "When you complete a transaction",
        "When you contact customer support",
        "From your device when you use the app or website",
        "From merchants and business customers",
        "From banks and payment service providers",
        "From identity verification and KYC providers",
        "From fraud-prevention and compliance service providers",
        "From publicly available sources where legally permitted",
        "From other authorized third parties",
      ] },
    ],
  },
  {
    id: "how-we-use",
    title: "4. How We Use Your Information",
    blocks: [
      { p: "We may use your personal information for the following purposes:" },
      { h: "4.1 Providing Our Services" },
      { p: "We use your information to:" },
      { list: ["Create and manage your account", "Process payments", "Facilitate QR payments", "Send and receive transaction information", "Provide merchant services", "Process refunds and reversals", "Provide customer support", "Maintain transaction records"] },
      { h: "4.2 Security and Fraud Prevention" },
      { p: "We may use information to:" },
      { list: ["Detect and prevent fraudulent transactions", "Identify suspicious activities", "Protect accounts", "Prevent unauthorized access", "Investigate security incidents", "Monitor unusual transaction patterns", "Protect BadePay users and merchants"] },
      { h: "4.3 Regulatory and Legal Compliance" },
      { p: "We may process information to:" },
      { list: ["Comply with applicable Nigerian laws and regulations", "Meet KYC requirements", "Meet AML and counter-terrorist financing requirements", "Respond to lawful requests from regulatory or law-enforcement authorities", "Maintain legally required records", "Meet reporting obligations"] },
      { h: "4.4 Improving BadePay" },
      { p: "We may use information to:" },
      { list: ["Improve our application", "Improve transaction performance", "Develop new products and services", "Analyze usage patterns", "Troubleshoot technical issues", "Conduct research and analytics", "Improve user experience"] },
      { h: "4.5 Communications" },
      { p: "We may use your information to send:" },
      { list: ["Transaction notifications", "Security alerts", "OTPs", "Service announcements", "Account-related communications", "Customer support communications", "Important legal or regulatory notices"] },
      { p: "Where legally permitted, we may also send promotional communications. You may opt out of marketing communications where applicable." },
    ],
  },
  {
    id: "legal-basis",
    title: "5. Legal Basis for Processing",
    blocks: [
      { p: "Where applicable, we process personal information on the basis of one or more of the following:" },
      { list: ["Your consent", "Performance of a contract or provision of requested services", "Compliance with a legal or regulatory obligation", "Protection of vital interests", "Legitimate interests, including security, fraud prevention and service improvement", "Other lawful bases permitted under applicable data protection laws"] },
      { p: "Where processing is based on consent, you may withdraw your consent where legally permitted. Withdrawal of consent does not affect the lawfulness of processing that occurred before withdrawal." },
    ],
  },
  {
    id: "sharing",
    title: "6. Sharing Your Information",
    blocks: [
      { callout: "BadePay does not sell your personal information." },
      { p: "We may share information with trusted third parties where necessary to provide the Services, comply with legal obligations, or protect users. These parties may include:" },
      { h: "Payment and Financial Partners" },
      { p: "Banks, payment processors, payment service providers, card networks, switching companies, and other financial institutions involved in processing transactions." },
      { h: "Identity Verification and Compliance Providers" },
      { p: "Third-party providers that assist with:" },
      { list: ["KYC", "Identity verification", "AML screening", "Sanctions screening", "Fraud detection"] },
      { h: "Technology and Infrastructure Providers" },
      { p: "Service providers that support:" },
      { list: ["Cloud hosting", "Data storage", "Cybersecurity", "Analytics", "Communications", "Customer support", "Software infrastructure"] },
      { h: "Professional Advisers" },
      { p: "We may share information with professional advisers such as lawyers, auditors, accountants, insurers, and consultants where reasonably necessary." },
      { h: "Government and Regulatory Authorities" },
      { p: "We may disclose information where required or permitted by law, including to regulators, courts, law-enforcement agencies, and other authorized government bodies." },
      { h: "Corporate Transactions" },
      { p: "If BadePay is involved in a merger, acquisition, restructuring, financing, sale of assets, or similar transaction, personal information may be transferred as part of that transaction, subject to applicable privacy requirements." },
    ],
  },
  {
    id: "transaction-sharing",
    title: "7. Information Shared During Transactions",
    blocks: [
      { p: "When you make a payment to a merchant or another BadePay user, certain information may be made available to the relevant parties to identify and process the transaction." },
      { p: "Depending on the transaction, this may include:" },
      { list: ["Name", "Merchant name", "Transaction reference", "Amount", "Date and time", "Transaction status"] },
      { p: "We only share information reasonably necessary to complete or support the transaction." },
    ],
  },
  {
    id: "third-party-services",
    title: "8. Third-Party Services",
    blocks: [
      { p: "BadePay may integrate with third-party services, including banks, payment processors, identity verification providers, analytics providers, cloud providers, and other technology providers." },
      { p: "These third parties may process information in accordance with their own privacy policies." },
      { p: "We encourage you to review the privacy policies of third-party services that you access through BadePay." },
    ],
  },
  {
    id: "cookies",
    title: "9. Cookies and Similar Technologies",
    blocks: [
      { p: "Our website and application may use cookies, SDKs, pixels, log files, and similar technologies to:" },
      { list: ["Keep you signed in", "Remember preferences", "Improve security", "Analyze usage", "Improve performance", "Detect fraudulent or abnormal activity", "Improve our services"] },
      { p: "You may be able to control cookies through your browser or device settings. Some functionality may not operate correctly if certain technologies are disabled." },
      { link: { href: "/cookies", label: "Read our Cookie Policy" } },
    ],
  },
  {
    id: "data-security",
    title: "10. Data Security",
    blocks: [
      { p: "We take reasonable technical and organizational measures to protect personal information against:" },
      { list: ["Unauthorized access", "Unauthorized disclosure", "Loss", "Misuse", "Alteration", "Destruction"] },
      { p: "Security measures may include encryption, access controls, authentication mechanisms, monitoring, logging, secure development practices, and other appropriate safeguards." },
      { p: "However, no electronic transmission or storage system can be guaranteed to be completely secure. You should also protect your account credentials, PIN, OTPs, and devices from unauthorized access." },
      { callout: "BadePay will never ask you to disclose your password, PIN, or OTP through an unsolicited email, SMS, or social media message." },
    ],
  },
  {
    id: "data-retention",
    title: "11. Data Retention",
    blocks: [
      { p: "We retain personal information only for as long as reasonably necessary for the purposes described in this Privacy Policy, including to:" },
      { list: ["Provide our Services", "Maintain transaction records", "Meet legal and regulatory obligations", "Resolve disputes", "Prevent fraud", "Enforce agreements", "Maintain appropriate business and financial records"] },
      { p: "Certain financial and transaction information may need to be retained for periods required by applicable laws and regulations, even after you close your account." },
    ],
  },
  {
    id: "international-transfers",
    title: "12. International Data Transfers",
    blocks: [
      { p: "Some of our service providers or technology infrastructure may be located outside Nigeria." },
      { p: "Where personal information is transferred outside Nigeria, we will take appropriate steps to ensure that such transfers are conducted in accordance with applicable data protection laws and appropriate safeguards." },
    ],
  },
  {
    id: "your-rights",
    title: "13. Your Privacy Rights",
    blocks: [
      { p: "Subject to applicable law, you may have rights relating to your personal information, including the right to:" },
      { list: [
        "Request access to personal information we hold about you",
        "Request correction of inaccurate or incomplete information",
        "Request deletion of personal information where legally applicable",
        "Request restriction of certain processing",
        "Object to certain processing",
        "Withdraw consent where processing is based on consent",
        "Request information about how your personal information is processed",
        "Request a copy of certain personal information in a portable format, where applicable",
        "Lodge a complaint with the relevant data protection authority",
      ] },
      { p: "Some requests may be subject to legal, regulatory, security, or contractual limitations." },
    ],
  },
  {
    id: "managing-account",
    title: "14. Managing Your Account",
    blocks: [
      { p: "You are responsible for ensuring that information associated with your BadePay account remains accurate and up to date." },
      { p: "You may update certain information through the BadePay application or by contacting our support team." },
      { p: "If you believe that your account has been compromised, you should contact BadePay immediately." },
    ],
  },
  {
    id: "childrens-privacy",
    title: "15. Children's Privacy",
    blocks: [
      { p: "BadePay is not intended for children who are below the minimum age permitted to use financial and payment services under applicable law." },
      { p: "We do not knowingly collect personal information from children in violation of applicable laws." },
      { p: "If you believe that a child has provided personal information to us improperly, please contact us so that we can investigate and take appropriate action." },
    ],
  },
  {
    id: "marketing",
    title: "16. Marketing Communications",
    blocks: [
      { p: "Where permitted by law, we may send you information about BadePay products, services, promotions, and updates." },
      { p: "You may opt out of promotional communications by following the unsubscribe instructions in the communication or by contacting us." },
      { p: "Please note that you may continue to receive essential service communications, including transaction alerts, security notifications, account notices, and other important messages." },
    ],
  },
  {
    id: "monitoring",
    title: "17. Fraud, Security and Compliance Monitoring",
    blocks: [
      { p: "Because BadePay provides payment-related services, we may monitor transactions, accounts, devices, and usage patterns to identify and prevent:" },
      { list: ["Fraud", "Money laundering", "Unauthorized transactions", "Account takeover", "Identity theft", "Cybersecurity threats", "Other unlawful or suspicious activities"] },
      { p: "Where required, information may be shared with relevant financial institutions, payment partners, regulators, law-enforcement agencies, or other authorized parties." },
    ],
  },
  {
    id: "changes",
    title: "18. Changes to This Privacy Policy",
    blocks: [
      { p: "We may update this Privacy Policy from time to time to reflect:" },
      { list: ["Changes to our Services", "Changes in technology", "Changes in applicable laws", "Regulatory requirements", "Changes in our business practices"] },
      { p: "When we make material changes, we may provide notice through the BadePay application, website, email, or other appropriate channels." },
      { p: "The updated Privacy Policy will become effective on the date stated at the beginning of the policy." },
    ],
  },
  {
    id: "privacy-requests",
    title: "19. Complaints and Privacy Requests",
    blocks: [
      { p: "If you have a question, concern, complaint, or request relating to your personal information, please contact our privacy team." },
      { contact: true },
      { p: "We will review and respond to privacy requests in accordance with applicable laws and regulatory requirements." },
    ],
  },
  {
    id: "contact-us",
    title: "20. Contact Us",
    blocks: [
      { p: "If you have any questions about this Privacy Policy or how BadePay handles personal information, please contact us:" },
      { contact: true },
      { link: { href: "/contact", label: "Go to the Contact page" } },
    ],
  },
];
